openapi: 3.0.0
info:
  title: Auth API
  version: 0.1.0

paths:
  /api/v1/auth/register:
    post:
      tags:
        - Auth
      summary: Регистрация пользователя
      requestBody:
        required: true
        description: Информация о пользователе
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                name:
                  type: string
                  example: Anna
                password:
                  type: string
                  example: 123456
                password2:
                  type: string
                  example: 123456
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponseRegister'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

        500:
          description: Server Interval Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

      security:
        - apiKeyAuth: []

  /api/health/live:
    get:
      tags:
        - Health
      summary: Health live
      responses:
        200:
          description: Healthy
          content:
            application/json:
              schema:
                type: string
                example: Health
        503:
          description: Unhealthy
          content:
            application/json:
              schema:
                type: string
                example: Unhealth

  /api/health/readiness:
    get:
      tags:
        - Health
      summary: Health readiness
      responses:
        200:
          description: Healthy
          content:
            application/json:
              schema:
                type: string
                example: "Healthy"
        503:
          description: Unhealthy
          content:
            application/json:
              schema:
                type: string
                example: "Unhealthy"

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

  schemas:
    SuccessResponseRegister:
      properties:
        code:
          type: string
          example: Created
          description: result string code
        status:
          type: string
          enum: [ok, fail]
        body:
          properties:
            id:
              type: integer
              format: int64
            email:
              type: string
              format: email
            name:
              type: string
              example: "name"
            createDate:
              type: integer
              format: int64
            tokens:
              properties:
                accessToken:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9  .eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                  description: jwt access token
                refreshToken:
                  type: string
                  example: "fdsfdsj321ob21"
                expiresAt:
                  type: integer
                  format: int64
                  example: 143094303
        error:
          type: string
          example: null
          description: error message

    ErrorResponse:
      properties:
        code:
          type: string
          example: "ERROR_STRING_CODE"
          description: result string code
        status:
          type: string
          enum: ["ok", "fail"]
        body:
          type: object
          example: null
        error:
          type: string
          example: "ERROR_MESSAGE"
          description: error message
